// @generated by microsandbox-types. Do not edit by hand.

export type EnvVar = {
  /**
   * Environment variable name.
   */
  key: string;
  /**
   * Environment variable value.
   */
  value: string;
};

export type CpuPlacement = "inherit" | "auto" | "spread" | "compact";

export type HandoffInit = {
  /**
   * Init binary: absolute path inside the guest rootfs, or the literal `auto`.
   *
   * Always a Linux-style `/`-separated path — never build it with host OS path APIs, whose semantics diverge on Windows (`\` separators, `/sbin/init` treated as relative).
   */
  cmd: string;
  /**
   * Supplemental argv. `argv[0]` is implicitly `cmd`.
   */
  args: Array<string>;
  /**
   * Extra env vars merged on top of the inherited env.
   */
  env: Array<[string, string]>;
};

export type SecurityProfile = "default" | "restricted";

export type SandboxPolicy = {
  /**
   * Whether the sandbox is ephemeral.
   *
   * Ephemeral sandboxes are one-off: the host runtime that owns the
   * process removes the persisted DB row and on-disk state when the VM
   * reaches a terminal status, and other host runtimes opportunistically
   * clean up ephemeral leftovers from runtimes that died before they
   * could self-clean. Defaults to `false` (persistent); named and created
   * sandboxes stay inspectable and restartable after they stop.
   */
  ephemeral: boolean;
  /**
   * Hard cap on total sandbox lifetime in seconds. `None` = run forever.
   */
  max_duration_secs: number | null;
  /**
   * Idle timeout in seconds. `None` = no idle detection.
   */
  idle_timeout_secs: number | null;
};

export type SandboxLogLevel = "error" | "warn" | "info" | "debug" | "trace";

export type MountOptions = {
  /**
   * Whether the mount is read-only.
   *
   * Guest writes fail with the kernel's read-only filesystem behavior. Virtiofs-backed mounts also reject writes on the host-side filesystem server as defense in depth.
   */
  readonly: boolean;
  /**
   * Whether direct execution from the mount is disabled.
   *
   * This prevents `execve` of binaries or scripts located on the mount. Interpreters can still read files from the mount, for example `sh /mnt/script.sh`, because the interpreter itself executes from a different filesystem.
   */
  noexec: boolean;
  /**
   * Whether setuid and setgid privilege elevation from files on the mount is ignored.
   */
  nosuid: boolean;
  /**
   * Whether device files on the mount are ignored.
   */
  nodev: boolean;
};

export type StatVirtualization = "strict" | "relaxed" | "off";

export type TransparentHugePagePolicy = "always" | "madvise" | "never";

export type HostPermissions = "private" | "mirror";

export type HostPattern = { "exact": string } | { "wildcard": string } | "any";

export type MintEndpoint = {
  /**
   * Exact hostname the request is addressed to, matched case-insensitively
   * against the TLS SNI. Bare host only: no scheme, port, path or userinfo.
   */
  host: string;
  /**
   * Exact request path, with no query string of its own.
   *
   * A request is matched on its path alone: whatever query the sandbox
   * appends, the endpoint it reached is this one. Must start with `/`.
   */
  path: string;
  /**
   * TCP port the endpoint is reached on. `None` is 443.
   *
   * The other endpoints carry their port in their URL and match on it;
   * this one is a host and a path, so it says its port here. A grant whose
   * inject host is served on another port names that port, or its mint
   * endpoint quietly never matches.
   */
  port?: number | null;
  /**
   * Top-level JSON field of the response that carries the minted secret.
   */
  field: string;
};

export type OAuthSecret = {
  /**
   * Host broker Unix-domain socket path.
   */
  broker_endpoint: string;
  /**
   * Opaque grant identifier understood by the broker.
   */
  grant_id: string;
  /**
   * Exact HTTPS token endpoint, including path and optional query.
   */
  token_endpoint: string;
  /**
   * Exact HTTPS device-code endpoint (RFC 8628), when the grant is obtained
   * by a device flow.
   *
   * Requests to it carry no grant material and are forwarded unmodified;
   * the endpoint only has to be known so the grant is loaded for the
   * connection that carries the rest of the device flow.
   */
  device_code_endpoint?: string | null;
  /**
   * Exact HTTPS device-code polling endpoint (RFC 8628).
   *
   * A `POST` here is a token request: a response carrying
   * [`access_token_field`](Self::access_token_field) is committed to the
   * broker and sanitized like a token-endpoint response, while the
   * `authorization_pending`, `slow_down`, `expired_token` and
   * `access_denied` errors are forwarded untouched. May be the same URL as
   * [`token_endpoint`](Self::token_endpoint).
   */
  poll_endpoint?: string | null;
  /**
   * Extra secret JSON fields in a poll response, such as the proprietary
   * `authorization_code` and `code_verifier` some providers return before
   * the real token exchange.
   *
   * Each is replaced with a sentinel before the guest sees it, and
   * substituted back on a later token request. The real values are held in
   * memory for the life of the connection that received them, so the
   * exchange has to happen on that connection.
   *
   * Only top-level string fields of the response object are inspected: a
   * secret nested inside another object, or under a field name that is not
   * listed here, stays on the verbatim path and reaches the sandbox.
   */
  poll_secret_fields: Array<string>;
  /**
   * Endpoints that mint a new long-lived secret in their response.
   *
   * A token endpoint hands back the grant's own tokens; these hand back
   * something else. Anthropic's console mode, for instance, `POST`s to
   * `https://api.anthropic.com/api/oauth/claude_cli/create_api_key` with
   * the access token and gets a fresh API key in `raw_key`. Nothing about
   * that key is known to the broker beforehand, so without an entry here
   * it reaches the sandbox in the clear.
   *
   * A `POST` to an exact host and path listed here whose 2xx JSON response
   * carries [`field`](MintEndpoint::field) as a top-level string is minted:
   * the broker stores the value and names a sentinel, the sandbox is handed
   * the sentinel instead, and later requests to this grant's inject hosts
   * have the sentinel substituted back.
   *
   * The host must be one of [`inject_hosts`](Self::inject_hosts) or the
   * token endpoint's host: a mint endpoint is loaded for its own host and
   * port, so one naming a host the grant says nothing else about is a
   * grant reaching somewhere it never declared.
   *
   * It is the endpoint's own host *and port* that load the grant, so an
   * endpoint served anywhere but 443 has to name its port in
   * [`port`](MintEndpoint::port) or the connection carrying it is never
   * recognised.
   */
  mint_endpoints: Array<MintEndpoint>;
  /**
   * Hosts where the access sentinel may be substituted.
   */
  inject_hosts: Array<HostPattern>;
  /**
   * JSON field carrying the access token in successful token responses.
   */
  access_token_field: string;
  /**
   * JSON field carrying the refresh token in successful token responses.
   *
   * May be the same field as
   * [`access_token_field`](Self::access_token_field): a device flow without
   * a refresh grant hands the same value back for both.
   */
  refresh_token_field: string;
  /**
   * Environment variable exposing the access sentinel to the guest.
   */
  access_env_var: string;
  /**
   * Environment variable exposing the refresh sentinel to the guest.
   */
  refresh_env_var: string;
  /**
   * Per-sandbox access-token sentinel, the value the guest starts with.
   *
   * It may be opaque, or JWT-shaped for a client that decodes the token to
   * read its claims: the real token's header and payload copied verbatim
   * with only the signature replaced. A JWT-shaped sentinel mirrors claims
   * that change on every login and refresh, so the broker may hand back a
   * replacement with the tokens it loads or commits, and that replacement
   * supersedes this value for the connection that received it.
   *
   * Must be non-empty, at most 8192 bytes (`MAX_OAUTH_SENTINEL_BYTES`),
   * and must not contain NUL, CR, or LF. No two sentinels, whether on this
   * grant or another, may be equal or contain one another.
   */
  access_sentinel: string;
  /**
   * Per-sandbox refresh-token sentinel, under the same rules as the access
   * sentinel above.
   */
  refresh_sentinel: string;
};

export type SecretInjection = {
  /**
   * Substitute in HTTP headers (default: true).
   */
  headers: boolean;
  /**
   * Substitute in HTTP Basic Auth (default: true).
   */
  basic_auth: boolean;
  /**
   * Substitute in URL query parameters (default: false).
   */
  query_params: boolean;
  /**
   * Substitute in request body (default: false).
   *
   * Fixed-length HTTP/1 bodies up to 16 MiB update `Content-Length`;
   * larger fixed-length bodies are blocked. Chunked HTTP/1 bodies are
   * decoded and re-encoded with fresh chunk sizes. Encoded bodies pass
   * through unchanged. HTTP/2 DATA-frame body substitution is not
   * supported; matching body placeholders are blocked.
   */
  body: boolean;
};

export type NetworkPolicy = {
  /**
   * Default action for egress traffic matching no rule. Default: `Deny`.
   */
  default_egress: Action;
  /**
   * Default action for ingress traffic matching no rule. Default: `Deny`.
   */
  default_ingress: Action;
  /**
   * Ordered rules, evaluated first-match-wins per direction.
   */
  rules: Array<Rule>;
};

export type Rule = {
  /**
   * Direction this rule applies to.
   */
  direction: Direction;
  /**
   * Destination filter (direction-dependent interpretation).
   */
  destination: Destination;
  /**
   * Protocol set; empty matches any protocol.
   */
  protocols: Array<Protocol>;
  /**
   * Guest-side port-range set; empty matches any port.
   */
  ports: Array<PortRange>;
  /**
   * Action to take on a match.
   */
  action: Action;
};

export type Action = "allow" | "deny";

export type Direction = "egress" | "ingress" | "any";

export type Protocol = "tcp" | "udp" | "icmpv4" | "icmpv6";

export type Destination = "any" | { "cidr": string } | { "domain": string } | {
  "domain_suffix": string;
} | { "group": DestinationGroup };

export type DestinationGroup =
  | "public"
  | "loopback"
  | "private"
  | "link_local"
  | "metadata"
  | "multicast"
  | "host";

export type PortRange = {
  /**
   * Start port (inclusive).
   */
  start: number;
  /**
   * End port (inclusive).
   */
  end: number;
};
